### PR TITLE
fix(internal): Require at least 1Mi for running

### LINKED ISSUE #1382: If user forgets to add "M" to the -M flag, kraft silently uses default memory amount
### Describe the bug

If user forgets to add "M" to the -M flag, kraft silently uses defaults memory amount, which can cause the app to fail without giving the user much indication as to why.

### Steps to reproduce

Run something like:

kraft run --rm -p 1313:1313 --plat qemu --arch x86_64 -M 512 # NOTE: no "M" after 512

on any app that requires more than the default amount of memory (which I think is 64M)

### Expected behavior

kraft should probably give an error, saying that the unit is missing, and stopping, rather than silently continuing, applying (silently again) the memory default, and then potentially failing if the app needs memory, without the user understanding why.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

macOS

### Relevant log output

```shell
% kraft run --rm -p 1313:1313 --plat qemu --arch x86_64 -M 512
 W  using hardware emulation
 i  using arch=x86_64 plat=qemu
[+] pulling unikraft.org/hugo:latest (qemu/x86_64) •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• 100% [1m 46s]
[+] building rootfs... done!                                                                                                                                    x86_64 [3.1s]
 E  machine fatally exited
```

### PR DESCRIPTION
**Pull request by craciunoiuc**
Lower values would get divided by Mi and turned to 0, which defaulted to 64Mi.

GitHub-Fixes: #1382

### Prerequisite checklist

  - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [ ] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### CODE REVIEW

File: internal/cli/kraft/run/run.go [hunk 1]
```diff
@@ -338,6 +348,7 @@ func (opts *RunOptions) Run(ctx context.Context, args []string) error {
 		if err != nil {
 			return err
 		}
+		fmt.Printf("quantity: %v\n", quantity)
```
Comment (nderjung) [inline internal/cli/kraft/run/run.go]: Lingering

**Review by nderjung — APPROVED** [review]
Thanks!
