### PR TITLE
fix: Do not run empty process lists

### LINKED ISSUE #681: `kraft pkg` hangs when wrong target is used
### Describe the bug

When using `kraft pkg` with the wrong target, it hangs.

### Steps to reproduce

The target name in `kraft.yaml` is `lua-qemu-x86_64-initrd`. I initialized the `TARGET_NAME` variable to a different value:

```console
export TARGET_NAME=lua-qemu-x86_64
```

then, the command below hanged:

```console
kraft pkg --target ${TARGET_NAME} --as oci --name unikraft.org/${TARGET_NAME}:latest --with-kconfig --initrd fs0.cpio
```

A variation using a custom runtime directory also failed:

```console
kraft pkg --runtime-dir ~/.local/kraftkit/runtime/ --target ${TARGET_NAME} --as oci --name unikraft.org/${TARGET_NAME}:latest --with-kconfig --initrd fs0.cpio
```

Running with debugging support didn't print out a relevant output (see logging out below):

```console
kraft --log-level trace --log-type basic pkg --runtime-dir ~/.local/kraftkit/runtime/ --target ${TARGET_NAME} --as oci --name unikraft.org/${TARGET_NAME}:latest --with-kconfig --initrd fs0.cpio
```

### Expected behavior

I would have expected an error message to be printed out.

### Which architectures were you using or does this bug affect?

_No response_

### Which operating system were you using or does this bug affect?

_No response_

### Relevant log output

```shell
T  http method=GET url=https://get.kraftkit.sh/latest.txt
 T  initializing package manager format=oci
 T  using oci directory handler path=/home/unikraft/.local/kraftkit/runtime/oci
 T  initializing package manager format=manifest
 T  checking if source is compatible with the manifest manager source=https://manifests.kraftkit.sh/index.yaml
 T  trying manifest provider path=https://manifests.kraftkit.sh/index.yaml
 T  http method=HEAD url=https://manifests.kraftkit.sh/index.yaml
 T  http method=GET url=https://manifests.kraftkit.sh/index.yaml
 T  trying index provider path=https://manifests.kraftkit.sh/index.yaml
 T  http method=HEAD url=https://manifests.kraftkit.sh/index.yaml
 T  http method=GET url=https://manifests.kraftkit.sh/index.yaml
 T  retrieved index path=https://manifests.kraftkit.sh/index.yaml
 T  using index provider path=https://manifests.kraftkit.sh/index.yaml
 T  skipping uninitialized target config file: could not open file: open /home/unikraft/maintainer-tools/workdir/apps/lua/.config.lua-qemu-x86_64-9pfs_qemu-x86_64: no such file or directory
 T  skipping uninitialized target config file: could not open file: open /home/unikraft/maintainer-tools/workdir/apps/lua/.config.lua-qemu-x86_64-initrd_qemu-x86_64: no such file or directory
 T  skipping uninitialized target config file: could not open file: open /home/unikraft/maintainer-tools/workdir/apps/lua/.config.lua-qemu-arm64-9pfs_qemu-arm64: no such file or directory
 T  skipping uninitialized target config file: could not open file: open /home/unikraft/maintainer-tools/workdir/apps/lua/.config.lua-qemu-arm64-initrd_qemu-arm64: no such file or directory
 T  skipping uninitialized target config file: could not open file: open /home/unikraft/maintainer-tools/workdir/apps/lua/.config.lua-fc-x86_64-initrd_fc-x86_64: no such file or directory
 T  skipping uninitialized target config file: could not open file: open /home/unikraft/maintainer-tools/workdir/apps/lua/.config.lua-fc-ar
m64-initrd_fc-arm64: no such file or directory
```

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

GitHub-Fixes: #681

### CODE REVIEW

File: tui/processtree/processtree.go [hunk 1]
```diff
@@ -77,6 +78,11 @@ type ProcessTree struct {
 }
 
 func NewProcessTree(ctx context.Context, opts []ProcessTreeOption, tree ...*ProcessTreeItem) (*ProcessTree, error) {
+	if len(tree) == 0 {
+		log.G(ctx).Debug("Process tree started with no processes")
+		return nil, fmt.Errorf("nothing to do")
+	}
```
Comment (nderjung) [inline tui/processtree/processtree.go]:
```diff
  	if len(tree) == 0 {
- 		log.G(ctx).Debug("Process tree started with no processes")
- 		return nil, fmt.Errorf("nothing to do")
+ 		return nil, fmt.Errorf("cannot instantiate process tree without sub processes")
  	}
```

File: cmd/kraft/pkg/pkg.go [hunk 2]
```diff
@@ -229,6 +229,11 @@ func (opts *Pkg) Run(cmd *cobra.Command, args []string) error {
 		}
 	}
 
+	if len(tree) == 0 {
+		return fmt.Errorf("no matching targets found for target=%s, platform=%s, architecture=%s",
+			opts.Target, opts.Platform, opts.Architecture)
+	}
```
Comment (nderjung) [inline cmd/kraft/pkg/pkg.go]:
```diff
- 	if len(tree) == 0 {
- 		return fmt.Errorf("no matching targets found for target=%s, platform=%s, architecture=%s",
- 			opts.Target, opts.Platform, opts.Architecture)
+ 	if len(tree) == 0 && len(opts.Target) > 0 {
+ 		return fmt.Errorf("no matching targets found for: %s", opts.Target)
+ 	} else if len(tree) == 0 && len(opts.Architecture) > 0 && len(opts.Platform) == 0 {
+ 		return fmt.Errorf("no matching targets found for architecture: %s", opts.Architecture)
+ 	} else if len(tree) == 0 && len(opts.Architecture) == 0 && len(opts.Platform) > 0 {
+ 		return fmt.Errorf("no matching targets found for platform: %s", opts.Platform)
+ 	} else if len(tree) == 0 {
+ 		return fmt.Errorf("no matching targets found for: %s/%s", opts.Platform, opts.Architecture)
  	}
```

**Review by jake-ciolek — APPROVED** [review]
