### PR TITLE
fix(internal): Delete empty `Makefile.uk` files on builds

### LINKED ISSUE #1196: `kraft build` creates empty `Makefile.uk` on builds
### Describe the bug

After building images for a given path, an empty `Makefile.uk` file appears which makes the git history of the repository dirty.

This should not be created, or at least should be removed.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Which architectures were you using or does this bug affect?

_No response_

### Which operating system were you using or does this bug affect?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

  - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [ ] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

GitHub-Closes: #1196

### CODE REVIEW

**Comment by nderjung** [comment]
Can you please open an issue on the core repo and reference it in the comment?

File: internal/cli/kraft/build/build.go [hunk 1]
```diff
@@ -141,6 +141,17 @@ func Build(ctx context.Context, opts *BuildOptions, args ...string) error {
 		return build.Statistics(ctx, opts, args...)
 	}
 
+	// NOTE(craciunoiuc): This is currently a workaround to remove empty
+	// Makefile.uk files generated wrongly by the build system. Until this
+	// is fixed we just delete.
```
Comment (nderjung) [inline internal/cli/kraft/build/build.go:146]:
```diff
  // NOTE(craciunoiuc): This is currently a workaround to remove empty
  // Makefile.uk files generated wrongly by the build system. Until this
  // is fixed we just delete.
+ //
+ // See: https://github.com/unikraft/unikraft/issues/1456
```

**Review by nderjung — APPROVED** [review]
Thanks!
