### PR TITLE
fix(kraft): Add better error guidance for version checks

### LINKED ISSUE #729: Add config option to disable checking for new versions
### Describe the bug

Checking for new Kraftkit versions happens when running every command, every time.
This is fine for any cable/land connection that has relatively low latency.
For satellite/phone/etc. connections this is really slow (1s+) and can make kraftkit appear blocked.

### Steps to reproduce

1. Start a hotspot on your phone
2. Connect phone to laptop
3. Wrap 95% of phone in tin foil
4. Try to run `kraft run`/build/whatever with `--log-level trace --log-type basic`
5. The command will pause for a lot of seconds before eventually erroring out and continuing

### Expected behavior

The command runs in reasonable time

### Which architectures were you using or does this bug affect?

_No response_

### Which operating system were you using or does this bug affect?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

Wanted to fix #729 but realised it was already fixed so I added a more descriptive debug message to it.

Closes: #729

### CODE REVIEW

**Review by jake-ciolek — APPROVED** [review]

File: cmd/kraft/kraft.go [hunk 1]
```diff
@@ -137,6 +137,7 @@ func main() {
 	if !config.G[config.KraftKit](ctx).NoCheckUpdates {
 		if err := kitupdate.Check(ctx); err != nil {
 			log.G(ctx).Debugf("could not check for updates: %v", err)
+			log.G(ctx).Debug("if you would like to disable update checks, set `no_check_updates: true` in the configuration file")
```
Comment (nderjung) [inline cmd/kraft/kraft.go]: Let's make this closer to [the existing message](https://github.com/unikraft/kraftkit/blob/staging/internal/update/update.go#L68-L88) with something like:
```go
log.G(ctx).Debugf("could not check for updates: %v", err)
log.G(ctx).Debug("")
log.G(ctx).Debug("to turn off this check, set:")
log.G(ctx).Debug("")
log.G(ctx).Debug("\texport KRAFTKIT_NO_CHECK_UPDATES=true")
log.G(ctx).Debug("")
log.G(ctx).Debug("or use the globally accessible flag '--no-check-updates'")
```

**Review by nderjung — APPROVED** [review]
Reviewed-by: Alexander Jung <alex@unikraft.io>
Approved-by: Alexander Jung <alex@unikraft.io>
