### PR TITLE
fix(cmd): properly stringify reflect.Value

### LINKED ISSUE #417: Command initialization fails on all primitive flag types except strings
We have a global issue with boolean values in commands' initialization.

It's also not too clear to me how a flag defined in `cmd/kraft/build` made its way in `cmd/kraft/version`.

It's failing here:

https://github.com/unikraft/kraftkit/blob/fbe71fd12aa075d0b1751ca13bedd118de202030/cmdfactory/builder.go#L198-L202

- The value of `name` is `"fast"`
- The value of `strValue` is `"<bool Value>"` (:exclamation:)

Inside `flags.Set`, `flag.Value.Set(strValue)` eventually calls `strconv.ParseBool(strValue)`, which fails with:

```
error(*strconv.NumError) *{
        Func: "ParseBool",
        Num: "<bool Value>",
        Err: error(*errors.errorString) *{
                s: "invalid syntax",},}
```

_Originally posted by @antoineco in https://github.com/unikraft/kraftkit/issues/414#issuecomment-1523290083_

### PR DESCRIPTION
**Pull request by antoineco**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [x] Updated relevant documentation.

### Description of changes

Fixes #417

Since Go 1.5, the `fmt` package prints the _concrete value_ of `reflect.Value` by default.
This is exactly what we want in order to be able to pass those underlying values to `flags.Set`.

Also includes minor typo fixes and code reorg.

---

Demo:

```go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	var myint int = 42
	var mybool bool = true
	var mystring string = "hello"

	fmt.Println(reflect.ValueOf(myint).String())
	fmt.Println(reflect.ValueOf(mybool).String())
	fmt.Println(reflect.ValueOf(mystring).String())

	fmt.Println(reflect.ValueOf(myint))
	fmt.Println(reflect.ValueOf(mybool))
	fmt.Println(reflect.ValueOf(mystring))
}
```

Output:
```
<int Value>
<bool Value>
hello
42
true
hello
```

### CODE REVIEW

File: cmdfactory/builder.go [hunk 1]
```diff
@@ -168,15 +169,14 @@ func AttributeFlags(c *cobra.Command, obj any, args ...string) {
 		}
 
 		switch fieldType.Type.Kind() {
-		case reflect.Int:
-			flags.IntVarP((*int)(unsafe.Pointer(v.Addr().Pointer())), name, alias, defInt, usage)
-			flags.Set(name, strValue)
-		case reflect.Int64:
-			flags.IntVarP((*int)(unsafe.Pointer(v.Addr().Pointer())), name, alias, defInt, usage)
```
Comment (craciunoiuc) [inline cmdfactory/builder.go]: Is the fix here related to the issue? What does this change affect?

Comment (antoineco) [reply cmdfactory/builder.go]: No, only the last commit is directly related.
This addresses duplicate code around the same location, but the change seems too insignificant for its own PR.

```
case reflect.Int:
  //
case reflect.Int64:
  //
```
->
```
case reflect.Int, case reflect.Int64:
  //
```

Comment (craciunoiuc) [reply cmdfactory/builder.go]: I was asking because you also removed the `flags.IntVarP((*...` line, and I was not sure what that changes

Comment (antoineco) [reply cmdfactory/builder.go]: Did I? Big oops!

Comment (antoineco) [reply cmdfactory/builder.go]: Fixed in [4e81a4e9..c2c64c84](https://github.com/unikraft/kraftkit/compare/4e81a4e9f38356b979ec9d9a23103136f772a7c1..c2c64c84924c99244d5228f28413558bb9650654)
Thanks for noticing!

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
