### PR TITLE
fix(lint): address errcheck, unused and ineffassign

### LINKED ISSUE #413: Address lint warnings
Enabling golangci-lint's default set of linters yields the following warnings:

```
config/feeder_yaml.go:169:17: Error return value is not checked (errcheck)
                recursiveMerge(from.Content[0], into.Content[0])
                              ^
archive/unarchive.go:108:13: Error return value of `os.Chtimes` is not checked (errcheck)
                os.Chtimes(path, header.AccessTime, header.ModTime)
                          ^
cmdfactory/builder.go:173:13: Error return value of `flags.Set` is not checked (errcheck)
                        flags.Set(name, strValue)
                                 ^
cmdfactory/builder.go:176:13: Error return value of `flags.Set` is not checked (errcheck)
                        flags.Set(name, strValue)
                                 ^
cmdfactory/builder.go:179:13: Error return value of `flags.Set` is not checked (errcheck)
                        flags.Set(name, strValue)
                                 ^
cmdfactory/builder.go:225:15: Error return value of `c.ParseFlags` is not checked (errcheck)
                c.ParseFlags(args)
                            ^
tui/processtree/processtree.go:97:24: Error return value of `pt.traverseTreeAndCall` is not checked (errcheck)
        pt.traverseTreeAndCall(tree, func(item *ProcessTreeItem) error {
                              ^
tui/processtree/update.go:23:24: Error return value of `pt.traverseTreeAndCall` is not checked (errcheck)
        pt.traverseTreeAndCall(pt.tree, func(pti *ProcessTreeItem) error {
                              ^
tui/processtree/update.go:44:25: Error return value of `pt.traverseTreeAndCall` is not checked (errcheck)
                pt.traverseTreeAndCall(pt.tree, func(pti *ProcessTreeItem) error {
                                      ^
unikraft/lib/library.go:289:9: Error return value of `fm.Seek` is not checked (errcheck)
        fm.Seek(0, io.SeekStart)
               ^
unikraft/app/application.go:381:15: Error return value of `tmpfile.Write` is not checked (errcheck)
        tmpfile.Write([]byte(values.String()))
                     ^
unikraft/app/application.go:382:14: Error return value of `tmpfile.Sync` is not checked (errcheck)
        tmpfile.Sync()
                    ^
unikraft/app/normalize.go:54:31: Error return value is not checked (errcheck)
        WithKraftfiles(absKraftfiles)(project)
                                     ^
unikraft/app/project_options.go:220:21: Error return value of `popts.AddKraftfile` is not checked (errcheck)
                popts.AddKraftfile(file)
                                  ^
unikraft/app/project_options.go:300:23: Error return value of `popts.AddKraftfile` is not checked (errcheck)
                                popts.AddKraftfile(candidates[0])
                                                  ^
machine/store.go:417:33: Error return value of `(*encoding/gob.Decoder).Decode` is not checked (errcheck)
                                if gob.NewDecoder(&b).Decode(&option); err != nil {
                                                            ^
oci/handler/containerd.go:96:12: Error return value is not checked (errcheck)
        defer done(ctx)
                  ^
oci/handler/containerd.go:193:36: Error return value of `(*encoding/json.Decoder).Decode` is not checked (errcheck)
                if json.NewDecoder(&cache).Decode(&manifest); err != nil {
                                                 ^
oci/oci.go:24:36: Error return value of `packmanager.RegisterPackageManager` is not checked (errcheck)
        packmanager.RegisterPackageManager(OCIFormat, NewOCIManager)
                                          ^
machine/qemu/qemu.go:663:14: Error return value of `qd.Destroy` is not checked (errcheck)
                        qd.Destroy(ctx, mid)
                                  ^
machine/qemu/qemu.go:993:13: Error return value of `watcher.Add` is not checked (errcheck)
        watcher.Add(mcfg.LogFile)
                   ^
machine/qemu/qemu.go:1271:10: Error return value of `qd.Stop` is not checked (errcheck)
                qd.Stop(ctx, mid)
                       ^
cmd/kraft/logs/logs.go:117:28: Error return value of `store.SaveMachineState` is not checked (errcheck)
                                        store.SaveMachineState(mid, status)
                                                              ^
cmd/kraft/logs/logs.go:134:20: Error return value of `driver.TailWriter` is not checked (errcheck)
                driver.TailWriter(ctx, mid, iostreams.G(ctx).Out)
                                 ^
cmd/kraft/logs/logs.go:143:10: Error return value of `io.Copy` is not checked (errcheck)
                io.Copy(iostreams.G(ctx).Out, fd)
                       ^
cmd/kraft/run/run.go:417:28: Error return value of `store.SaveMachineState` is not checked (errcheck)
                                        store.SaveMachineState(mid, status)
                                                              ^
cmd/kraft/run/run.go:443:20: Error return value of `driver.TailWriter` is not checked (errcheck)
                driver.TailWriter(ctx, mid, iostreams.G(ctx).Out)
                                 ^
cmd/kraft/events/events.go:89:16: Error return value of `pidfile.Write` is not checked (errcheck)
                pidfile.Write([]byte(fmt.Sprintf("%d", os.Getpid())))
                             ^
iostreams/console.go:37:6: func `enableVirtualTerminalProcessing` is unused (unused)
func enableVirtualTerminalProcessing(f *os.File) error {
     ^
iostreams/tty_size.go:35:6: func `ttySize` is unused (unused)
func ttySize() (int, int, error) {
     ^
unikraft/lib/library.go:84:2: field `origin` is unused (unused)
        origin string
        ^
unikraft/lib/library.go:94:2: field `projectdir` is unused (unused)
        projectdir string
        ^
unikraft/lib/library.go:100:2: field `patchdir` is unused (unused)
        patchdir string
        ^
utils/utils.go:142:2: ineffectual assignment to ns (ineffassign)
        ns /= 1000
        ^
oci/handler/containerd.go:69:3: ineffectual assignment to namespace (ineffassign)
                namespace = "default"
                ^
```

### PR DESCRIPTION
**Pull request by antoineco**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [x] Updated relevant documentation.

### Description of changes

Fixes #413

### CODE REVIEW

File: unikraft/lib/library.go [hunk 1]
```diff
@@ -79,26 +79,15 @@ type LibraryConfig struct {
...
-	// projectdir is the root location of the project that this library is a
-	// member of.
-	projectdir string
-
 	// path is the location to this library within the context of a project.
 	path string
 
-	// patchdir is the directory where patches to the origin library are kept.
-	patchdir string
-
```
Comment (nderjung) [inline unikraft/lib/library.go]: Whilst these are currently unused, we should not remove them because they are essentially future items that need to be referenced and so removing them may make us forget it.

To get around this we should export these internal attributes via public interface methods.

Comment (antoineco) [reply unikraft/lib/library.go]: It's future because you know about it and have your own conception of how _you_ want to use them, but as-is it is dead code.

I suggest we comment these fields, not hack-export them. But ideally this code should only exist in a branch where it is being actively worked on as part of a concrete feature.

Comment (antoineco) [reply unikraft/lib/library.go]: I commented the fields in [4b56ec2a..252bb66f](https://github.com/unikraft/kraftkit/compare/4b56ec2aa2ca80b4cd7183f999ae51917e84504e..252bb66f3ef2e07eca15a5e2b4fa81e354207a60).

But like I mentioned, if the code only exists in one developer's head, it has no place in a shared codebase IMO.

Comment (antoineco) [reply unikraft/lib/library.go]: Would you mind creating a feature request referring to that part of the code, describing what needs to be done?

Comment (antoineco) [reply unikraft/lib/library.go]: Created #429

Comment (nderjung) [reply unikraft/lib/library.go]: Thanks for taking care of this!

**Review by nderjung — APPROVED** [review]
Looks good! Thanks a lot!

Approved-by: Alexander Jung <alex@unikraft.io>
