### PR TITLE
fix(initrd): Warn on panics possibly related to docker

### LINKED ISSUE #2001: kraftkit Examples not working on Arch without proper Docker setup
### Describe the bug

During the Unikraft Workshop we discovered that kraftkit does not give a proper error message on Arch LInux if Docker is not installed/started/we do not have the correct permissions. 

### Steps to reproduce

Install kraftkit-bin from the AUR and don't start docker beforehand

### Expected behavior

An error message that docker needs to be started/installed/user has correct permissions

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/arch

### Relevant log output

```shell
i  use --as=kraftfile-runtime to skip this prompt in the future
Caught panic:

checked path: $XDG_RUNTIME_DIR

Restoring terminal...

goroutine 232 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc000143900)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:705 +0x91
panic({0x1e63bc0?, 0xc00048d3f8?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/testcontainers/testcontainers-go/internal/core.MustExtractDockerHost.func1()
	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/internal/core/docker_host.go:91 +0x66
sync.(*Once).doSlow(0xc000aabc30?, 0xc000aabc80?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/testcontainers/testcontainers-go/internal/core.MustExtractDockerHost({0x2592198?, 0x37abcc0?})
	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/internal/core/docker_host.go:88 +0x58
github.com/testcontainers/testcontainers-go/internal/core.NewClient({0x2592198, 0x37abcc0}, {0x0, 0x0, 0x0?})
	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/internal/core/client.go:17 +0x88
github.com/testcontainers/testcontainers-go.NewDockerClientWithOpts({0x2592198, 0x37abcc0}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/docker_client.go:117 +0x71
github.com/testcontainers/testcontainers-go.NewDockerProvider({0xc0007ab560, 0x2, 0x21c1d7f?})
	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/provider.go:143 +0x10f
github.com/testcontainers/testcontainers-go.ProviderType.GetProvider(0x0, {0xc000aace28, 0x1, 0x586d1a?})
	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/provider.go:114 +0x3e5
github.com/testcontainers/testcontainers-go.GenericContainer({_, _}, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...})
	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/generic.go:59 +0x139
kraftkit.sh/initrd.(*dockerfile).Build(0xc000181c20, {0x25920b8, 0xc00071d6b0})
	/__w/kraftkit/kraftkit/initrd/dockerfile.go:283 +0xad9
kraftkit.sh/internal/cli/kraft/utils.BuildRootfs.func1({0x25920b8?, 0xc00071d6b0?})
	/__w/kraftkit/kraftkit/internal/cli/kraft/utils/rootfs.go:55 +0x63
kraftkit.sh/tui/processtree.(*ProcessTree).Init.(*ProcessTree).waitForProcessCmd.func2()
	/__w/kraftkit/kraftkit/tui/processtree/processtree.go:334 +0x11a
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:324 +0x86
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 227
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:318 +0x139
 E  could not prepare deployment: could not package: could not package: could not build rootfs: program was killed: context canceled
```

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

  - [ ] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [ ] Tested your changes against relevant architectures and platforms;
  - [ ] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

GitHub-Closes: #2001

### CODE REVIEW

File: initrd/dockerfile.go [hunk 1]
```diff
@@ -215,6 +215,43 @@ func (initrd *dockerfile) Name() string {
...
+	// For more information see:
+	//
+	// https://github.com/unikraft/kraftkit/issues/2001
+	defer func() {
+		if r := recover(); r != nil {
+			log.G(ctx).Warn("Recovered from BuildKit instantiation panic.")
+			log.G(ctx).Warn("This can be caused by Docker missing from the system, or being inaccesible.")
+			log.G(ctx).Warn("")
+			log.G(ctx).Warn("If you think this was caused by something else, please open an issue at:")
+			log.G(ctx).Warn("https://github.com/unikraft/kraftkit/issues")
```
Comment (nderjung) [inline initrd/dockerfile.go]:
```diff
-			log.G(ctx).Warn("Recovered from BuildKit instantiation panic.")
-			log.G(ctx).Warn("This can be caused by Docker missing from the system, or being inaccesible.")
-			log.G(ctx).Warn("")
-			log.G(ctx).Warn("If you think this was caused by something else, please open an issue at:")
-			log.G(ctx).Warn("https://github.com/unikraft/kraftkit/issues")
+			log.G(ctx).Warn("recovered from BuildKit instantiation panic!")
+			log.G(ctx).Warn("this can be caused by Docker missing from the system, or from being inaccesible")
+			log.G(ctx).Warn("")
+			log.G(ctx).Warn("if you think this was caused by something else, please open an issue at:")
+			log.G(ctx).Warn("https://github.com/unikraft/kraftkit/issues")
```

**Review by nderjung — CHANGES_REQUESTED** [review]

**Review by nderjung — APPROVED** [review]
Thanks!

Reviewed-by: Alexander Jung <alex@unikraft.io>
Approved-by: Alexander Jung <alex@unikraft.io>
