### PR TITLE
fix(unikraft): Do not append library prefix for all libraries

### LINKED ISSUE #645: `kraft build` does not configure the application properly if the app is not on one of `unikraft` organisation branches
### Describe the bug

Running `kraft build` from a repository while checked out on a branch that is not part of the `unikraft` organisation (e.g. fetching to a pull request) will cause the configuration to not add external libraries from `kraft.yaml`.

For example:

```console
$ git clone https://github.com/unikraft/app-helloworld-cpp
$ cd app-helloworld-cpp/
$ gh pr checkout 13 # this will checkout on another branch
$ kraft build

[...]

$ cat .config.helloworld-cpp_qemu-x86_64 | grep -i libcxx
# CONFIG_LIBCXXABI is not set
# CONFIG_LIBCXX is not set
```

The `libcxx` and `libcxxabi` libraries are present in the `kraft.yaml` file.
Also for whatever reason the `musl` library gets selected, but not any other.

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

Should eventually be replaced by #653 

Fixes the bug presented in #645, but for that example it will fail in the next step (the build), as libraries are not in the correct order. #653 will be the proper fix for this.

GitHub-Closes: #645

### CODE REVIEW

File: unikraft/lib/library.go [hunk 1]
```diff
@@ -190,7 +190,15 @@ func (lc LibraryConfig) KConfigTree(_ context.Context, env ...*kconfig.KeyValue)
 func (lc LibraryConfig) KConfig() kconfig.KeyValueMap {
 	values := kconfig.KeyValueMap{}
 	values.OverrideBy(lc.kconfig)
-	values.Set(kconfig.Prefix+"LIB"+strings.ToUpper(lc.name), kconfig.Yes)
+
+	// TODO (#653) temporary check as not all libraries follow the same
+	// naming convention. Will be replaced by the kconfig parser.
```
Comment (nderjung) [inline unikraft/lib/library.go]:
```
// TODO(craciunoiuc): Temporary check as ...
// See: https://github.com/unikraft/kraftkit/issue/653
```

File: unikraft/lib/library.go [hunk 2]
```diff
@@ -190,7 +190,16 @@ func (lc LibraryConfig) KConfigTree(_ context.Context, env ...*kconfig.KeyValue)
 func (lc LibraryConfig) KConfig() kconfig.KeyValueMap {
 	values := kconfig.KeyValueMap{}
 	values.OverrideBy(lc.kconfig)
-	values.Set(kconfig.Prefix+"LIB"+strings.ToUpper(lc.name), kconfig.Yes)
+
+	// TODO (craciunoiuc): Temporary check as not all libraries follow the same
```
Comment (nderjung) [inline unikraft/lib/library.go]: Pedantic, but no space:
```diff
- TODO (craciunoiuc)
+ TODO(craciunoiuc)
```

Comment (craciunoiuc) [reply unikraft/lib/library.go]: :magic_wand:

**Review by nderjung — APPROVED** [review]
