### PR TITLE
fix: Preserve original user's config path when running with sudo

### LINKED ISSUE #992: `kraft net` almost unusable with multiple users
### Describe the bug

Trying to use the `kraft net` subcommands together with `kraft run` is almost impossible when using multiple users.

In order to create a network interface you need to use `sudo`, and then you should be able to use it inside `kraft run`.

But, to use it there, you also need to use `sudo` for `kraft run`. This means that the user is changed and the path to the config also becomes changed (effectively using the home of `root`).

This can prove confusing as people ca run:
1. `sudo kraft run`
1. `kraft ps`

And then see no output, even though they should.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Which architectures were you using or does this bug affect?

x86_64, arm, arm64

### Which operating system were you using or does this bug affect?

linux/debian, linux/fedora, linux/alpine, linux/arch, linux/other

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ijaidev**
# fix: Preserve original user's config path when running with sudo

## Description

Fixes #992

When `kraft` is invoked via `sudo`, `os.UserHomeDir()` returns `/root`, causing machine state to be stored in `/root/.local/share/kraftkit/runtime/` instead of the user's home directory. This makes machines created with `sudo kraft run` invisible to non-sudo commands like `kraft ps`.

### `config/config_file.go`
- Added `getSudoUserInfo()` - detects sudo via `SUDO_USER` environment variable and retrieves the original user's UID, GID, and home directory
- Added `getHomeDir()` - returns the original user's home directory when running under sudo
- Added `ChownToUser()` / `ChownToUserRecursive()` - fixes file ownership for files created by sudo
- Updated `ConfigDir()`, `StateDir()`, `DataDir()` to use `getHomeDir()` instead of `os.UserHomeDir()`

### Machine Drivers
Added `config.ChownToUser(machine.Status.StateDir)` after directory creation in:
- `machine/firecracker/v1alpha1.go`
- `machine/qemu/v1alpha1.go`
- `machine/xen/v1alpha1.go`

### `store/embedded.go`
- Added `config.ChownToUserRecursive(store.path)` after BadgerDB operations
- Restructured `Create()` and `Delete()` to close DB before chowning (ensures files written during close() get correct ownership)

## Testing

**Before this fix:**
```bash
$ sudo kraft run --plat fc -d ./build/app
machine_name

$ kraft ps -a
NAME  KERNEL  ARGS  CREATED  STATUS  MEM  PORTS  PLAT
# Empty - machine not visible!
```

**After this fix:**
```bash
$ sudo kraft run --plat fc -d ./build/app
compassionate_missbaker

$ kraft ps -a   # WITHOUT sudo ✓
NAME                     KERNEL  STATUS  PLAT
compassionate_missbaker  pr...   exited  fc
```

**File ownership:**
```bash
$ ls -la ~/.local/share/kraftkit/runtime/machinev1alpha1/
drwx------ 2 jaidev jaidev 000001.sst
drwx------ 2 jaidev jaidev 000002.sst
drwx------ 2 jaidev jaidev 000003.sst  # Previously owned by root!
```

## Checklist

- [x] Code follows project conventions
- [x] Commit message follows contribution guidelines
- [x] `make fmt` passes
- [x] Manual testing completed

### CODE REVIEW

File: config/config_file.go [hunk 1]
```diff
@@ -42,6 +44,105 @@ const (
...
+	info := getSudoUserInfo()
+	if info == nil || info.UID == 0 {
+		return nil
+	}
+
+	return filepath.Walk(path, func(name string, fileInfo os.FileInfo, err error) error {
+		if err != nil {
+			return err
+		}
+		return os.Chown(name, info.UID, info.GID)
```
Comment (craciunoiuc) [inline config/config_file.go]: Would it be faster to only chown files/dirs that are owned by `root`?

File: config/config_file.go [hunk 2]
```diff
@@ -42,6 +44,105 @@ const (
...
+}
+
+// getHomeDir returns the appropriate home directory for kraftkit configuration.
+// When running under sudo, this returns the original user's home directory
+// to maintain consistent config paths between privileged and unprivileged commands.
+func getHomeDir() string {
+	if info := getSudoUserInfo(); info != nil {
+		return info.HomeDir
+	}
+	homeDir, _ := os.UserHomeDir()
```
Comment (craciunoiuc) [inline config/config_file.go]: Can you log the error as a warning now that we do it in a central function?

File: machine/qemu/v1alpha1.go [hunk 3]
```diff
@@ -159,6 +159,11 @@ func (service *machineV1alpha1Service) Create(ctx context.Context, machine *mach
 		return machine, err
 	}
 
+	// Ensure the directory is owned by the original user when running under sudo
+	if err := config.ChownToUser(machine.Status.StateDir); err != nil {
```
Comment (craciunoiuc) [inline machine/qemu/v1alpha1.go]: The state directory is chowned, but what about the files inside? I guess these are also checked for?

File: store/embedded.go [hunk 4]
```diff
@@ -138,19 +145,30 @@ func (store *embedded[_, _]) Create(ctx context.Context, key string, _, out runt
...
+		return err
+	}
+
+	// Close the database first, then chown all files
+	if err := store.close(); err != nil {
+		return err
+	}
+
+	// Ensure any new files created during the transaction are owned by the original user
+	return config.ChownToUserRecursive(store.path)
```
Comment (craciunoiuc) [inline store/embedded.go]: In this case, in case of a failure the file is not chowned, I think this si not intended?

I would suggest you do something like

```
defer func() {
	store.close()
	config.ChownToUserRecursive(store.path)
}
```

File: store/embedded.go [hunk 5]
```diff
@@ -159,17 +177,27 @@ func (store *embedded[_, _]) Delete(ctx context.Context, key string, out runtime
...
```
Comment (craciunoiuc) [inline store/embedded.go]: Same as above?

**Review by craciunoiuc — CHANGES_REQUESTED** [review]
Some comments my side. Changes look good.

We need to decide if we should handle all cases, or only the cases where a "mandatory sudo" might happen

File: config/config_file.go (hunk 1 above)
Comment (ijaidev) [reply config/config_file.go]: you are right 
I have updated it

File: config/config_file.go (hunk 2 above)
Comment (ijaidev) [reply config/config_file.go]: done

File: machine/qemu/v1alpha1.go (hunk 3 above)
Comment (ijaidev) [reply machine/qemu/v1alpha1.go]: done, updated recursively

File: store/embedded.go (hunk 4 above)
Comment (ijaidev) [reply store/embedded.go]: you are right, 
I have updated the code

File: store/embedded.go (hunk 5 above)
Comment (ijaidev) [reply store/embedded.go]: done

File: config/config_file.go (hunk 1 above)
Comment (craciunoiuc) [reply config/config_file.go]: I see you added:
```
			if stat.Uid != 0 {
				return nil
			}
```

I would go even further to say this should be `stat.Uid != info.Uid` or something like this. This would cover the very rare case where a different user creates files in another user's home directory

File: config/config_file.go [hunk 6]
```diff
@@ -42,6 +45,114 @@ const (
...
+// Returns nil if not running under sudo or if the original user cannot be determined.
+func getSudoUserInfo() *sudoUserInfo {
+	sudoUser := os.Getenv("SUDO_USER")
+	if sudoUser == "" {
+		return nil
+	}
+
+	// Try to get UID/GID from environment first (more reliable)
+	uidStr := os.Getenv("SUDO_UID")
+	gidStr := os.Getenv("SUDO_GID")
```
Comment (craciunoiuc) [inline config/config_file.go]:
```suggestion
	sudoUser := os.Getenv("SUDO_USER") // <--
	if sudoUser == "" {
		return nil
	}

	// Try to get UID/GID from environment first (more reliable)
	uidStr := os.Getenv("SUDO_UID") // <--
	gidStr := os.Getenv("SUDO_GID") // <--
```

Can you make sure those env variables also exist in MacOS?

File: config/config_file.go [hunk 7]
```diff
@@ -42,6 +45,114 @@ const (
...
+	info := getSudoUserInfo()
+	if info == nil || info.UID == 0 {
+		return nil
+	}
+
+	return filepath.Walk(path, func(name string, fileInfo os.FileInfo, err error) error {
+		if err != nil {
+			return err
+		}
+		if stat, ok := fileInfo.Sys().(*syscall.Stat_t); ok {
```
Comment (craciunoiuc) [inline config/config_file.go]: I think this should work on `Mac`, I'm not 100% sure, but seems fine.

Still, I would highly suggest you move this function to a separate `config/utils_unix.go` and create a separate `config/utils_windows.go` where you stub it.

I know we don't really support compiling windows at this time, but it's better to have at least stubbed compatibility.

Move there also the `getSudoUserInfo` function as it's also Unix specific (so all, but not windows)

File: .github/workflows/tests.yaml [hunk 8]
```diff
@@ -139,6 +139,8 @@ jobs:
           KRAFTKIT_NO_WARN_SUDO: true
           KRAFTKIT_NO_CHECK_UPDATES: true
           DOCKER: ''
+          XDG_DATA_HOME: /tmp/kraftkit-data
```
Comment (craciunoiuc) [inline .github/workflows/tests.yaml]: `XDG_*` Variables are Mac specific

I understand why this fix worked in the context of Kraftkit (checks are in order), but it's hacky to do this 😔 

I would suggest we do this properly and add variables for the other fields also like we have for:
```
	if a := os.Getenv(KRAFTKIT_CONFIG_DIR); a != "" {
		path = a
	}
```

So that will be a similar change for `KRAFTKIT_STATE_DIR` and `KRAFTKIT_DATA_DIR`.

And here in this file you would set `KRAFTKIT_STATE_DIR` and `KRAFTKIT_DATA_DIR` to these same values

File: config/utils_unix.go [hunk 9]
```diff
@@ -0,0 +1,152 @@
...
+//
+// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+// SOFTWARE.
+
+//go:build unix
```
Comment (craciunoiuc) [inline config/utils_unix.go]: Did this work? can you also try `!windows` instead of `unix`?

File: config/config_file.go [hunk 10]
```diff
@@ -70,41 +71,46 @@ func ConfigDir() string {
...
 	var path string
-	if a := os.Getenv(XDG_STATE_HOME); a != "" {
-		path = filepath.Join(a, "kraftkit")
-	} else if b := os.Getenv(LOCAL_APP_DATA); runtime.GOOS == "windows" && b != "" {
-		path = filepath.Join(b, "KraftKit")
+	if a := os.Getenv(KRAFTKIT_STATE_DIR); a != "" {
+		path = a
+	} else if b := os.Getenv(XDG_STATE_HOME); b != "" {
+		path = filepath.Join(b, "kraftkit")
+	} else if c := os.Getenv(LOCAL_APP_DATA); runtime.GOOS == "windows" && c != "" {
```
Comment (craciunoiuc) [inline config/config_file.go]:
```suggestion
	} else if c := os.Getenv(LOCAL_APP_DATA); c != "" {
```

File: config/config_file.go [hunk 11]
```diff
@@ -70,41 +71,46 @@ func ConfigDir() string {
...
 	var path string
-	if a := os.Getenv(XDG_DATA_HOME); a != "" {
-		path = filepath.Join(a, "kraftkit")
-	} else if b := os.Getenv(LOCAL_APP_DATA); runtime.GOOS == "windows" && b != "" {
-		path = filepath.Join(b, "KraftKit")
+	if a := os.Getenv(KRAFTKIT_DATA_DIR); a != "" {
+		path = a
+	} else if b := os.Getenv(XDG_DATA_HOME); b != "" {
+		path = filepath.Join(b, "kraftkit")
+	} else if c := os.Getenv(LOCAL_APP_DATA); runtime.GOOS == "windows" && c != "" {
```
Comment (craciunoiuc) [inline config/config_file.go]:
```suggestion
	} else if c := os.Getenv(LOCAL_APP_DATA); c != "" {
```

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by ijaidev** [comment]
Glad to contribute!
